NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /
rest :
    type : rest
    resource : "routing_rest.yml"
    prefix : /api
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"