teckboard_core:
    resource: "@TeckboardCoreBundle/Controller"
    type:     annotation
login_check:
    pattern:   /login_check
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"