<?php

namespace Teckboard\Teckboard\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BoardAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoardAccountRepository extends EntityRepository
{
}
