<?php

namespace Teckboard\Teckboard\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WidgetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectorRepository extends EntityRepository
{
}
